{
 "title": "RED Method for MySQL Queries - Designed for PMM2",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters", "label": "Filters" },
   {
    "name": "NodeName",
    "query": "SELECT DISTINCT node_name from pmm.metrics where service_type='mysql'"
   }
  ]
 },
 "panels": [
  { "title": "About Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "\n# RED Method Analyses for MySQL Query Performance \n\nThis dashboard accessess data in Clickhouse directly.  Use Filters for ad-hoc filtering of the data set\nFor More Information on READ Method Check Out  [RED Method](https://thenewstack.io/monitoring-microservices-red-method/)\n\n\n\n"
  },
  { "title": "RED Method Analyses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(num_queries)/avg(period_length) as QPS\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Total Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(num_queries_with_errors)/sum(num_queries) as ErrorRate\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Total Query Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(m_query_time_sum)/sum(m_query_time_cnt) as AvgLatency,\n    avg(m_query_time_p99) as p99Latency\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Query Rate Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(num_queries)/avg(period_length) as QPS,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t,node_name\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": " Error Rate Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(num_queries_with_errors)/sum(num_queries) as ErrorRate,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t,node_name \nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Avg  Query Latency Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(m_query_time_sum)/sum(m_query_time_cnt) as AvgLatency,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t,node_name\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "RED for $NodeName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "NodeName",
   "collapsed": true,
   "panels": [
    {
     "title": "Query Rate - $NodeName",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "database": "pmm",
       "dateTimeColDataType": "period_start",
       "dateTimeType": "DATETIME",
       "rawSql": "SELECT\n    period_start AS t,\n    sum(num_queries)/avg(period_length) as QPS\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and node_name='$NodeName'\nGROUP BY t\nORDER BY t",
       "round": "1m"
      }
     ]
    },
    {
     "title": "Error Rate - $NodeName",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "database": "pmm",
       "dateTimeColDataType": "period_start",
       "dateTimeType": "DATETIME",
       "rawSql": "SELECT\n    period_start AS t,\n    sum(num_queries_with_errors)/sum(num_queries) as ErrorRate\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and node_name='$NodeName'\nGROUP BY t\nORDER BY t",
       "round": "1m"
      }
     ]
    },
    {
     "title": "Query Latency - $NodeName",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "database": "pmm",
       "dateTimeColDataType": "period_start",
       "dateTimeType": "DATETIME",
       "rawSql": "SELECT\n    period_start AS t,\n    sum(m_query_time_sum)/sum(m_query_time_cnt) as AvgLatency,\n    avg(m_query_time_p99) as p99Latency\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and node_name='$NodeName'\nGROUP BY t\nORDER BY t",
       "round": "1m"
      }
     ]
    }
   ]
  },
  { "title": "Additional Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Row Based Efficiency (Total)",
   "type": "graph",
   "description": "Number of Rows Examined per Row Sent to the client or modified.   The lower the number the more efficiently database is doing the work.  Values above 100 tend to correspond to missing indexes or inefficient queries which crunch a lot of data",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    {
     "format": "short",
     "label": "Rows Examined Per Row Sent or Affected"
    }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(m_rows_examined_sum)/sum(m_rows_sent_sum+m_rows_affected_sum) as Rows_exam_per_action,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t,node_name\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Time Based Efficiency (Total)",
   "type": "graph",
   "description": "Average time it takes for database to produce row to sent to client or  modify row.   When database is running efficiently it should take fraction of millisecond ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    {
     "format": "s",
     "label": "Query Time per Row Sent/Affected"
    }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(m_query_time_sum)/sum(m_rows_sent_sum+m_rows_affected_sum) as Time_per_row_action,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t,node_name\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Queries Per Host ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(num_queries)/avg(period_length) as QPS,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime )\nGROUP BY t,node_name\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Query Load Per Host",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Average Active Queries" }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(m_query_time_sum)/avg(period_length) as Load,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime )\nGROUP BY t,node_name\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "READ Query Time Based Efficiency",
   "type": "graph",
   "description": "For READ Queries how much time is spent per Row Sent.  Values above 1ms tend to correspond to seriously inefficient system",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s", "label": "Rows Examined Per Row Sent" }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(m_query_time_sum*(m_rows_sent_sum>0))/sum(m_rows_sent_sum) as Time_per_row_sent,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t,node_name\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "READ Query  Data Crunching Efficiency",
   "type": "graph",
   "description": "For READ Queries how many rows/sec is system able to crunch.  Low values tend to correspond to poor CPU performance,  Poor Cache efficiency, contention.  Higher values means \"work\" is being done more efficiently but it may be wrong work, for example scanning tables with no indexes",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    {
     "format": "ops",
     "label": "Rows Examined per Query Exec Sec"
    }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(m_rows_examined_sum*(m_rows_sent_sum>0))/sum(m_query_time_sum*(m_rows_sent_sum>0)) as Rows_Examined_QuerySec,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t,node_name\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "WRITE Query Time Based Efficiency",
   "type": "graph",
   "description": "For WRITE Queries how much time is spent per Row Sent.  Values above 1ms tend to correspond to seriously inefficient system",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s", "label": "Rows Examined Per Row Sent" }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(m_query_time_sum*(m_rows_affected_sum>0))/sum(m_rows_affected_sum) as Time_per_row_affected,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t,node_name\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "WRITE Query  Data Crunching Efficiency",
   "type": "graph",
   "description": "For WRITE Queries how many rows/sec is system able to crunch.  Low values tend to correspond to poor CPU performance,  Poor Cache efficiency, contention.  Higher values means \"work\" is being done more efficiently but it may be wrong work, for example scanning tables with no indexes",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    {
     "format": "ops",
     "label": "Rows Examined per Query Exec Sec"
    }
   ],
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    period_start AS t,\n    sum(m_rows_examined_sum*(m_rows_affected_sum>0))/sum(m_query_time_sum*(m_rows_affected_sum>0)) as Rows_Examined_QuerySec,\n    node_name\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type='mysql'\nGROUP BY t,node_name\nORDER BY t",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Frequent Queries",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    fingerprint,\n    node_name as Host, schema \"Schema\",\n    sum(num_queries)/(toUnixTimestamp($__toTime) - toUnixTimestamp($__fromTime))*1000 QPS,\n    sum(m_query_time_sum)/sum(m_query_time_cnt)*1000 as Latency_ms,\n    sum(m_rows_examined_sum)/sum(m_rows_sent_sum) as Rows_exam_per_sent\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime )\nGROUP BY node_name,Schema,fingerprint\nORDER BY QPS desc limit 20",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Slowest Queries",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    fingerprint, node_name as Host, schema \"Schema\",\n    sum(num_queries)/(toUnixTimestamp($__toTime) - toUnixTimestamp($__fromTime))*1000 QPS,\n    sum(m_query_time_sum)/sum(m_query_time_cnt)*1000 as Latency_ms,\n    sum(m_rows_examined_sum)/sum(m_rows_sent_sum) as Rows_exam_per_sent\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime )\nGROUP BY fingerprint,node_name,schema\nORDER BY Latency_ms desc limit 20",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Queries Causing the Load",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT period_start AS t, count() FROM pmm.metrics WHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) GROUP BY t ORDER BY t",
     "rawSql": "SELECT\n    fingerprint,\n    node_name as Host, schema \"Schema\",\n    sum(m_query_time_sum)/(toUnixTimestamp($__toTime) - toUnixTimestamp($__fromTime))*1000 Load,\n    sum(num_queries)/(toUnixTimestamp($__toTime) - toUnixTimestamp($__fromTime))*1000 QPS,\n    sum(m_query_time_sum)/sum(m_query_time_cnt)*1000 as Latency_ms,\n    sum(m_rows_examined_sum)/sum(m_rows_sent_sum) as Rows_exam_per_sent\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime )\nGROUP BY  node_name,Schema,fingerprint\nORDER BY Load desc limit 20",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Queries with Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    fingerprint,node_name as Host, schema \"Schema\",\n    sum(num_queries_with_errors) Errors,\n    sum(num_queries)/(toUnixTimestamp($__toTime) - toUnixTimestamp($__fromTime))*1000 QPS,\n    sum(m_query_time_sum)/sum(m_query_time_cnt)*1000 as Latency_ms,\n    sum(m_rows_examined_sum)/sum(m_rows_sent_sum) as Rows_exam_per_sent\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime )\nGROUP BY node_name, schema, fingerprint\nHaving Errors>0\nORDER BY Errors desc limit 20",
     "round": "1m"
    }
   ]
  },
  {
   "title": "Queries with Warnings",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "pmm",
     "dateTimeColDataType": "period_start",
     "dateTimeType": "DATETIME",
     "rawSql": "SELECT\n    fingerprint,node_name as Host, schema \"Schema\",\n    sum(num_queries_with_warnings) Warnings,\n    sum(num_queries)/(toUnixTimestamp($__toTime) - toUnixTimestamp($__fromTime))*1000 QPS,\n    sum(m_query_time_sum)/sum(m_query_time_cnt)*1000 as Latency_ms,\n    sum(m_rows_examined_sum)/sum(m_rows_sent_sum) as Rows_exam_per_sent\nFROM pmm.metrics\nWHERE ( period_start  >= $__fromTime AND period_start <= $__toTime )\nGROUP BY fingerprint,node_name,schema\nHaving Warnings>0\nORDER BY Warnings desc limit 20",
     "round": "1m"
    }
   ]
  }
 ]
}